version: "3.9"

services:
  api-gateway:
    image: ${DOCKER_USERNAME}/api-gateway:latest
    container_name: api-gateway
    restart: always

    ports:
      - "4000:4000"       # public port

    environment:
      PORT: 4000
      AUTH_SERVICE_URL: "http://user-service:4001"
      POST_SERVICE_URL: "http://post-service:4002"
      FOLLOW_SERVICE_URL: "http://comment-service:4003"
      NEWS_FEED_SERVICE_URL: "http://news-feed-service:4004"

    networks:
      - system

networks:
  system:
    driver: bridge