name: Build and Deploy API Gateway

on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted

    steps:
      # Source code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Build binary
      - name: Build Go binary
        run: |
          cd services/api-gateway
          go mod tidy
          go build -o api-gateway .

      # Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest \
            ./services/api-gateway

      # Push lên Docker Hub
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull latest image
        run: |
          echo "Pulling new API Gateway image..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest

      - name: Deploy service
        run: |
          echo "Restarting API Gateway service..."
          cd /home/ubuntu/deploy
          docker compose up -d api-gateway
          echo "Deployment completed!"