name: API Gateway CI/CD

on:
  push:
    branches:
      - develop
    paths:
      - "../../microservices/api-gateway/**"
  pull_request:
    branches:
      - develop
    paths:
      - "../../microservices/api-gateway/**"

jobs:
  run_api_gateway:
    uses: dauthang81197/system-design-new-feed/.github/workflows/api-gateway.yml@develop
    with:
      is_deploy: ${{ github.event_name == 'push' }}
    secrets: inherit
